---

- name: deploy db server
  hosts: db

  roles:
    - role: dbrole
      tags: dbtag
      database_name: 'foo'

- name: deploy web server
  hosts: web

  roles:
    - role: webrole
      tags: webtag

