---

- name: deploy db server
  hosts: db

  roles:
    - role: dbrole
      tags: dbtag

- name: deploy web server
  hosts: web

  roles:
    - role: webrole
      tags: webtag

- name: ntp
  hosts: all

  roles:
    - role: ntprole
