---

- name: Install webserver packages
  become: true
  package:
    name: "{{ web_pkg[ansible_facts['distribution']] }}"
    state: present

- name: Configure webserver .conf file
  become: true
  ansible.builtin.lineinfile:
    path: "{{ web_conf[ansible_facts['distribution']] }}"
    regexp: '^\s*Listen\s+'
    line: "Listen {{ web_port }}"
    firstmatch: yes
    state: present

- name: Configure SELinux for httpd on that port
  become: true
  shell: "/usr/sbin/semanage port -a -t http_port_t -p tcp {{ web_port }}"
  register: result
  when: ansible_selinux is defined and ansible_selinux != False and ansible_selinux.status == 'enabled'
  failed_when: result.rc != 0 and 'already defined' not in result.stderr

- name: Start webserver
  become: true
  ansible.builtin.systemd:
    name: "{{ web_pkg[ansible_facts['distribution']] }}"
    enabled: yes
    state: started
