---

- hosts: debian
  become: true
  tasks:
    - name: Install zip tools on debian
      apt: name={{item}} state=present
      with_items:
        - zip
        - zipcmp
        - zipmerge
        - ziptime
