---

- name: Install postgresql packages
  become: true
  package:
    name: "{{ db_pkg }}"
    state: present

- name: Check whether db already setup
  stat:
    path: '/var/lib/pgsql/data/postgresql.conf'
  register: result

- name: Initialise postgresql db
  become: true
  command: '/usr/bin/postgresql-setup initdb'
  when: not result.stat.exists

