---

- hosts: all
  become: true
  tasks:
    - name: Create group bobgrp
      group:
        name: bobgrp
        state: present
    - name: Create user bob
      user:
        name: bob
        state: present
        shell: /bin/bash
        system: false
        createhome: true
        group: bobgrp
        home: /home/bob
    - name: Create new bash profile
      template:
        src: templates/bash_profile.j2
        dest: /home/bob/.bash_profile
        owner: bob
        group: bobgrp
        mode: 0600
        backup: true
